name: Debug Metadata

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  integration-tests:
    name: Run TGI Integration Tests
    runs-on:
      group: gcp-ct5lp-hightpu-8t
    
    steps:
      - name: Install DNS utilities
        run: |
          sudo apt-get update -y
          sudo apt-get install -y dnsutils iputils-ping curl

      - name: Debug metadata
        run: |
          echo "Checking DNS configuration..."
          echo "nslookup metadata.google.internal"
          # Configure DNS server with recursion
          echo "options timeout:1" > /tmp/resolv.conf
          echo "nameserver 10.211.128.10" >> /tmp/resolv.conf
          echo "options edns0" >> /tmp/resolv.conf
          sudo mv /tmp/resolv.conf /etc/resolv.conf

          # Perform DNS lookup
          nslookup metadata.google.internal

          echo "ping -c 3 metadata.google.internal"
          ping -c 3 metadata.google.internal

          echo "ping -c 3 169.254.169.254"
          ping -c 3 169.254.169.254

          echo "Get the IP address of metadata.google.internal using getent"
          METADATA_IP=$(getent hosts metadata.google.internal | awk '{ print $1 }')
          echo "Metadata server IP address: ${METADATA_IP}"
          
          echo "curl -s http://metadata.google.internal/computeMetadata/v1/instance/image -H Metadata-Flavor: Google"
          curl "http://metadata.google.internal/computeMetadata/v1/instance/image" -H "Metadata-Flavor: Google"
