name: Debug Metadata

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  integration-tests:
    name: Run TGI Integration Tests
    runs-on:
      group: gcp-ct5lp-hightpu-8t
    
    steps:
      - name: Install DNS utilities
        run: |
          sudo apt-get update -y
          sudo apt-get install -y dnsutils iputils-ping curl bind9 bind9utils

      - name: Configure DNS recursion
        run: |
          # Backup original configuration
          sudo cp /etc/bind/named.conf.options /etc/bind/named.conf.options.backup || true
          
          # Create new configuration with recursion enabled
          sudo tee /etc/bind/named.conf.options << EOF
          options {
              directory "/var/cache/bind";
              recursion yes;
              allow-recursion { any; };
              dnssec-validation auto;
              auth-nxdomain no;
              listen-on { any; };
              listen-on-v6 { any; };
              forward only;
              forwarders {
                  8.8.8.8;
                  8.8.4.4;
              };
          };
          EOF
          
          # Restart bind9 service
          sudo systemctl restart bind9 || sudo service bind9 restart
          
          # Wait for DNS to be ready
          sleep 5

      - name: Debug metadata
        run: |
          echo "nslookup metadata.google.internal"
          nslookup metadata.google.internal

          echo "ping -c 3 metadata.google.internal"
          ping -c 3 metadata.google.internal

          echo "ping -c 3 169.254.169.254"
          ping -c 3 169.254.169.254

          echo "Get the IP address of metadata.google.internal using getent"
          # Get the IP address of metadata.google.internal using getent
          METADATA_IP=$(getent hosts metadata.google.internal | awk '{ print $1 }')
          echo "Metadata server IP address: ${METADATA_IP}"
          
          echo "curl -s http://metadata.google.internal/computeMetadata/v1/instance/image -H Metadata-Flavor: Google"
          # Try to access the metadata server
          curl "http://metadata.google.internal/computeMetadata/v1/instance/image" -H "Metadata-Flavor: Google"