name: Debug Metadata

on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  integration-tests:
    name: Run TGI Integration Tests
    runs-on:
      group: gcp-ct5lp-hightpu-8t
    
    steps:
      - name: Install DNS utilities
        run: |
          sudo apt-get update -y
          sudo apt-get install -y dnsutils iputils-ping curl

      - name: Configure DNS resolution
        run: |
          # Backup the current resolv.conf
          sudo cp /etc/resolv.conf /etc/resolv.conf.backup
          
          # Remove the symlink if it exists
          sudo rm -f /etc/resolv.conf
          
          # Create new resolv.conf
          sudo tee /etc/resolv.conf << EOF
          nameserver 169.254.169.254
          nameserver 8.8.8.8
          nameserver 8.8.4.4
          search google.internal
          options timeout:1
          EOF

      - name: Debug metadata
        run: |
          echo "nslookup metadata.google.internal"
          nslookup metadata.google.internal

          echo "ping -c 3 metadata.google.internal"
          ping -c 3 metadata.google.internal

          echo "ping -c 3 169.254.169.254"
          ping -c 3 169.254.169.254

          echo "Get the IP address of metadata.google.internal using getent"
          # Get the IP address of metadata.google.internal using getent
          METADATA_IP=$(getent hosts metadata.google.internal | awk '{ print $1 }')
          echo "Metadata server IP address: ${METADATA_IP}"
          
          echo "curl -s http://metadata.google.internal/computeMetadata/v1/instance/image -H Metadata-Flavor: Google"
          # Try to access the metadata server
          curl "http://metadata.google.internal/computeMetadata/v1/instance/image" -H "Metadata-Flavor: Google"