name: Optimum TPU / Test TGI on TPU / Integration Tests

on:
  push:
  pull_request:
    branches: [ main ]
    paths:
      - "text-generation-inference/**"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  integration-tests:
    name: Run TGI Integration Tests
    runs-on:
      group: gcp-ct5lp-hightpu-8t

    container:
      image: us-central1-docker.pkg.dev/tpu-pytorch-releases/docker/xla:r2.4.0_3.10_tpuvm
      options: >-
        --shm-size "16gb"
        --ipc host
        --privileged
        ${{ vars.V5_LITEPOD_8_ENV}}
        -v /var/run/docker.sock:/var/run/docker.sock
        -v /mnt/hf_cache:/mnt/hf_cache

    env:
      PJRT_DEVICE: TPU
      HF_HUB_CACHE: /mnt/hf_cache/cache_huggingface
      HF_TOKEN: ${{ secrets.HF_TOKEN_OPTIMUM_TPU_CI }}
      DOCKER_VOLUME: /mnt/hf_cache
      PYTHONUNBUFFERED: 1
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
      DEBIAN_FRONTEND: noninteractive
      SKIP_PROTOC: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          # Update and install required packages with retry
          for i in {1..3}; do
            apt-get update && \
            apt-get install -y \
              apt-transport-https \
              ca-certificates \
              curl \
              gnupg \
              lsb-release \
              protobuf-compiler \
              libprotobuf-dev \
              docker.io && break || sleep 15
          done
          
          # Verify protoc installation
          protoc --version
          
          # Configure Docker daemon
          mkdir -p /etc/docker
          echo '{
            "default-network-mode": "host",
            "registry-mirrors": ["https://mirror.gcr.io"]
          }' > /etc/docker/daemon.json
          
          # Start Docker
          service docker start || true
          timeout 30s bash -c 'until docker info; do sleep 1; done'

      - name: Install Python dependencies
        run: |
          python -m pip install --no-cache-dir \
            protobuf \
            grpcio-tools \
            mypy-protobuf

      - name: Build and test
        run: |
          make tgi_docker_integration_test_installs
          DOCKER_RUN_ARGS="--network host" python -m pytest -sv text-generation-inference/integration-tests